return {
    [1] = {'WAR','WAR'},
    [2] = {'WAR','THF'},
    [3] = {'WAR','WAR'},
    [4] = {'WAR','WAR'},
    [5] = {'WAR','WAR'},
    [6] = {'WAR','WAR'},
    [7] = {'WAR','WAR'},
    [8] = {'WAR','WAR'},
    [9] = {'WAR','WAR'},
    [10] = {'PLD','PLD'},
    [11] = {'WAR','WAR'},
    [12] = {'WAR','WAR'},
    [13] = {'MNK','MNK'},

    [15] = {'WAR','WAR'},
    [16] = {'WAR','WAR'},
    [17] = {'WAR','WAR'},
    [18] = {'MNK','MNK'},
    [19] = {'WAR','WAR'},
    [20] = {'WAR','WAR'},
    [21] = {'WAR','WAR'},
    [22] = {'DRK','WAR'},
    [23] = {'BLM','BLM'},



    [27] = {'WAR','WAR'},
    [28] = {'PLD','PLD'},
    [29] = {'WAR','WAR'},
    [30] = {'WAR','WAR'},
    [31] = {'WAR','WAR'},
    [32] = {'WAR','WAR'},
    [33] = {'WAR','WAR'},
    [34] = {'DRK','DRK'},
    [35] = {'THF','THF'},
    [36] = {'PLD','PLD'},
    [37] = {'THF','THF'},
    [38] = {'WAR','THF'},




    [43] = {'WAR','WAR'},
    [44] = {'WAR','WAR'},
    [45] = {'PLD','PLD'},
    [46] = {'WAR','WAR'},
    [47] = {'WAR','WAR'},
    [48] = {'WAR','WAR'},
    [49] = {'WAR','WAR'},


    [52] = {'WAR','WAR'},
    [53] = {'BLM','WAR'},
    [54] = {'BLM','WAR'},

    [56] = {'WAR','WAR'},
    [57] = {'WAR','WAR'},
    [58] = {'WAR','WAR'},

    [60] = {'PLD','PLD'},
    [61] = {'SAM','BLM'},
    [62] = {'WAR','WAR'},
    [63] = {'PLD','PLD'},
    [64] = {'WAR','WAR'},
    [65] = {'DRK','BLM'},
    [66] = {'WAR','WAR'},


    [69] = {'WAR','WAR'},
    [70] = {'WAR','WAR'},
    [71] = {'WHM','BRD'},
    [72] = {'WAR','WAR'},
    [73] = {'THF','BLM'},
    [74] = {'MNK','MNK'},
    [75] = {'RDM','RDM'},
    [76] = {'WAR','BLM'},




    [256] = {'WAR','BLM'},
    [257] = {'WAR','WHM'},
    [258] = {'WHM','BLM'},
    [259] = {'DRK','THF'},
    [261] = {'WHM','THF'},
    [262] = {'WAR','WAR'},
    [263] = {'WAR','WAR'},


    [266] = {'WAR','BLM'},
    [267] = {'RDM','BLM'},
    [268] = {'RDM','BLM'},
    [269] = {'WAR','BLM'},

    [271] = {'WAR','WAR'},
    [272] = {'WAR','BLM'},




    [277] = {'WAR','WAR'},
    [278] = {'WAR','WAR'},
    [279] = {'WAR','WAR'},
    [280] = {'WAR','BLM'},
    [281] = {'MNK','BLM'},
    [282] = {'MNK','WHM'},
    [283] = {'MNK','MNK'},
    [284] = {'RDM','MNK'},
    [285] = {'MNK','MNK'},

    [287] = {'MNK','NIN'},
    [288] = {'WAR','RDM'},
    [289] = {'DRK','BLM'},
    [290] = {'WAR','RDM'},
    [291] = {'WAR','BLM'},
    [292] = {'PLD','BLM'},
    [293] = {'PLD','RDM'},
    [294] = {'WAR','RDM'},
    [295] = {'WHM','BLM'},
    [296] = {'WHM','BLM'},
    [297] = {'WAR','RDM'},
    [298] = {'WAR','BLM'},
    [299] = {'DRK','BLM'},
    [300] = {'WAR','DRK'},
    [301] = {'WAR','RDM'},
    [302] = {'WAR','BLM'},
    [303] = {'DRK','BLM'},
    [304] = {'DRK','DRK'},
    [305] = {'THF','BLM'},

    [307] = {'WAR','PLD'},
    [308] = {'BLM','PLD'},
    [309] = {'RDM','THF'},
    [310] = {'BLM','THF'},


    [315] = {'WAR','BLM'},
    [316] = {'WAR','WAR'},
    [317] = {'WAR','WAR'},
    [318] = {'PLD','PLD'},
    [319] = {'PLD','RDM'},
    [320] = {'PLD','BLM'},
    [321] = {'WAR','BLM'},
    [322] = {'WAR','BLM'},
    [323] = {'WAR','BLM'},
    [324] = {'WAR','BLM'},



    [329] = {'RDM','WAR'},
    [330] = {'THF','WAR'},
    [331] = {'PLD','DRK'},
    [332] = {'WAR','WAR'},
    [333] = {'WHM','PLD'},
    [334] = {'WAR','WAR'},
    [335] = {'WAR','BLM'},
    [336] = {'WAR','WAR'},
    [337] = {'DRK','WAR'},
    [340] = {'PLD','RDM'},
    [341] = {'BLM','PLD'},
    [342] = {'RDM','PLD'},
    [343] = {'DRK','PLD'},
    [344] = {'COR','COR'},
    [345] = {'SAM','WHM'},
    [346] = {'PLD','BLM'},
    [347] = {'WAR','WAR'},
    [348] = {'DRK','WAR'},
    [349] = {'BRD','BLM'},
    [350] = {'RDM','BRD'},
    [351] = {'THF','BLM'},
    [352] = {'BLM','WAR'},
    [353] = {'WAR','RDM'},
    [354] = {'BLM','BRD'},
    [355] = {'WAR','WAR'},
    [356] = {'RDM','WAR'},
    [357] = {'RDM','WAR'},
    [358] = {'NIN','MNK'},
    [359] = {'BRD','THF'},
    [360] = {'BLM','WAR'},


    [508] = {'WAR','WAR'},
    [509] = {'BLM','WAR'},
    [510] = {'WAR','BLM'},
    [511] = {'BLM','WAR'},
}